# basic options
title: CSE2016 프로그램설계방법론
author: 도경구
email: doh@hanyang.ac.kr
description: 한양대학교 ERICA 소프트웨어학부 2020년 2학기
twitter_username:
github_username: Doggzone

# Build settings
markdown: kramdown
theme: minima